package com.shop.model.merchant;

import java.util.ArrayList;
import java.util.List;

public class ItemExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop_items
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop_items
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop_items
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_items
     *
     * @mbg.generated
     */
    public ItemExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_items
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_items
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_items
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_items
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_items
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_items
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_items
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_items
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_items
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_items
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shop_items
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andItemsIdIsNull() {
            addCriterion("items_id is null");
            return (Criteria) this;
        }

        public Criteria andItemsIdIsNotNull() {
            addCriterion("items_id is not null");
            return (Criteria) this;
        }

        public Criteria andItemsIdEqualTo(Integer value) {
            addCriterion("items_id =", value, "itemsId");
            return (Criteria) this;
        }

        public Criteria andItemsIdNotEqualTo(Integer value) {
            addCriterion("items_id <>", value, "itemsId");
            return (Criteria) this;
        }

        public Criteria andItemsIdGreaterThan(Integer value) {
            addCriterion("items_id >", value, "itemsId");
            return (Criteria) this;
        }

        public Criteria andItemsIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("items_id >=", value, "itemsId");
            return (Criteria) this;
        }

        public Criteria andItemsIdLessThan(Integer value) {
            addCriterion("items_id <", value, "itemsId");
            return (Criteria) this;
        }

        public Criteria andItemsIdLessThanOrEqualTo(Integer value) {
            addCriterion("items_id <=", value, "itemsId");
            return (Criteria) this;
        }

        public Criteria andItemsIdIn(List<Integer> values) {
            addCriterion("items_id in", values, "itemsId");
            return (Criteria) this;
        }

        public Criteria andItemsIdNotIn(List<Integer> values) {
            addCriterion("items_id not in", values, "itemsId");
            return (Criteria) this;
        }

        public Criteria andItemsIdBetween(Integer value1, Integer value2) {
            addCriterion("items_id between", value1, value2, "itemsId");
            return (Criteria) this;
        }

        public Criteria andItemsIdNotBetween(Integer value1, Integer value2) {
            addCriterion("items_id not between", value1, value2, "itemsId");
            return (Criteria) this;
        }

        public Criteria andItemsTitleIsNull() {
            addCriterion("items_title is null");
            return (Criteria) this;
        }

        public Criteria andItemsTitleIsNotNull() {
            addCriterion("items_title is not null");
            return (Criteria) this;
        }

        public Criteria andItemsTitleEqualTo(String value) {
            addCriterion("items_title =", value, "itemsTitle");
            return (Criteria) this;
        }

        public Criteria andItemsTitleNotEqualTo(String value) {
            addCriterion("items_title <>", value, "itemsTitle");
            return (Criteria) this;
        }

        public Criteria andItemsTitleGreaterThan(String value) {
            addCriterion("items_title >", value, "itemsTitle");
            return (Criteria) this;
        }

        public Criteria andItemsTitleGreaterThanOrEqualTo(String value) {
            addCriterion("items_title >=", value, "itemsTitle");
            return (Criteria) this;
        }

        public Criteria andItemsTitleLessThan(String value) {
            addCriterion("items_title <", value, "itemsTitle");
            return (Criteria) this;
        }

        public Criteria andItemsTitleLessThanOrEqualTo(String value) {
            addCriterion("items_title <=", value, "itemsTitle");
            return (Criteria) this;
        }

        public Criteria andItemsTitleLike(String value) {
            addCriterion("items_title like", value, "itemsTitle");
            return (Criteria) this;
        }

        public Criteria andItemsTitleNotLike(String value) {
            addCriterion("items_title not like", value, "itemsTitle");
            return (Criteria) this;
        }

        public Criteria andItemsTitleIn(List<String> values) {
            addCriterion("items_title in", values, "itemsTitle");
            return (Criteria) this;
        }

        public Criteria andItemsTitleNotIn(List<String> values) {
            addCriterion("items_title not in", values, "itemsTitle");
            return (Criteria) this;
        }

        public Criteria andItemsTitleBetween(String value1, String value2) {
            addCriterion("items_title between", value1, value2, "itemsTitle");
            return (Criteria) this;
        }

        public Criteria andItemsTitleNotBetween(String value1, String value2) {
            addCriterion("items_title not between", value1, value2, "itemsTitle");
            return (Criteria) this;
        }

        public Criteria andCategoryOneIsNull() {
            addCriterion("category_one is null");
            return (Criteria) this;
        }

        public Criteria andCategoryOneIsNotNull() {
            addCriterion("category_one is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryOneEqualTo(String value) {
            addCriterion("category_one =", value, "categoryOne");
            return (Criteria) this;
        }

        public Criteria andCategoryOneNotEqualTo(String value) {
            addCriterion("category_one <>", value, "categoryOne");
            return (Criteria) this;
        }

        public Criteria andCategoryOneGreaterThan(String value) {
            addCriterion("category_one >", value, "categoryOne");
            return (Criteria) this;
        }

        public Criteria andCategoryOneGreaterThanOrEqualTo(String value) {
            addCriterion("category_one >=", value, "categoryOne");
            return (Criteria) this;
        }

        public Criteria andCategoryOneLessThan(String value) {
            addCriterion("category_one <", value, "categoryOne");
            return (Criteria) this;
        }

        public Criteria andCategoryOneLessThanOrEqualTo(String value) {
            addCriterion("category_one <=", value, "categoryOne");
            return (Criteria) this;
        }

        public Criteria andCategoryOneLike(String value) {
            addCriterion("category_one like", value, "categoryOne");
            return (Criteria) this;
        }

        public Criteria andCategoryOneNotLike(String value) {
            addCriterion("category_one not like", value, "categoryOne");
            return (Criteria) this;
        }

        public Criteria andCategoryOneIn(List<String> values) {
            addCriterion("category_one in", values, "categoryOne");
            return (Criteria) this;
        }

        public Criteria andCategoryOneNotIn(List<String> values) {
            addCriterion("category_one not in", values, "categoryOne");
            return (Criteria) this;
        }

        public Criteria andCategoryOneBetween(String value1, String value2) {
            addCriterion("category_one between", value1, value2, "categoryOne");
            return (Criteria) this;
        }

        public Criteria andCategoryOneNotBetween(String value1, String value2) {
            addCriterion("category_one not between", value1, value2, "categoryOne");
            return (Criteria) this;
        }

        public Criteria andCategoryTwoIsNull() {
            addCriterion("category_two is null");
            return (Criteria) this;
        }

        public Criteria andCategoryTwoIsNotNull() {
            addCriterion("category_two is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryTwoEqualTo(String value) {
            addCriterion("category_two =", value, "categoryTwo");
            return (Criteria) this;
        }

        public Criteria andCategoryTwoNotEqualTo(String value) {
            addCriterion("category_two <>", value, "categoryTwo");
            return (Criteria) this;
        }

        public Criteria andCategoryTwoGreaterThan(String value) {
            addCriterion("category_two >", value, "categoryTwo");
            return (Criteria) this;
        }

        public Criteria andCategoryTwoGreaterThanOrEqualTo(String value) {
            addCriterion("category_two >=", value, "categoryTwo");
            return (Criteria) this;
        }

        public Criteria andCategoryTwoLessThan(String value) {
            addCriterion("category_two <", value, "categoryTwo");
            return (Criteria) this;
        }

        public Criteria andCategoryTwoLessThanOrEqualTo(String value) {
            addCriterion("category_two <=", value, "categoryTwo");
            return (Criteria) this;
        }

        public Criteria andCategoryTwoLike(String value) {
            addCriterion("category_two like", value, "categoryTwo");
            return (Criteria) this;
        }

        public Criteria andCategoryTwoNotLike(String value) {
            addCriterion("category_two not like", value, "categoryTwo");
            return (Criteria) this;
        }

        public Criteria andCategoryTwoIn(List<String> values) {
            addCriterion("category_two in", values, "categoryTwo");
            return (Criteria) this;
        }

        public Criteria andCategoryTwoNotIn(List<String> values) {
            addCriterion("category_two not in", values, "categoryTwo");
            return (Criteria) this;
        }

        public Criteria andCategoryTwoBetween(String value1, String value2) {
            addCriterion("category_two between", value1, value2, "categoryTwo");
            return (Criteria) this;
        }

        public Criteria andCategoryTwoNotBetween(String value1, String value2) {
            addCriterion("category_two not between", value1, value2, "categoryTwo");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(Double value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(Double value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(Double value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(Double value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(Double value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<Double> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<Double> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(Double value1, Double value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(Double value1, Double value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andStockIsNull() {
            addCriterion("stock is null");
            return (Criteria) this;
        }

        public Criteria andStockIsNotNull() {
            addCriterion("stock is not null");
            return (Criteria) this;
        }

        public Criteria andStockEqualTo(Integer value) {
            addCriterion("stock =", value, "stock");
            return (Criteria) this;
        }

        public Criteria andStockNotEqualTo(Integer value) {
            addCriterion("stock <>", value, "stock");
            return (Criteria) this;
        }

        public Criteria andStockGreaterThan(Integer value) {
            addCriterion("stock >", value, "stock");
            return (Criteria) this;
        }

        public Criteria andStockGreaterThanOrEqualTo(Integer value) {
            addCriterion("stock >=", value, "stock");
            return (Criteria) this;
        }

        public Criteria andStockLessThan(Integer value) {
            addCriterion("stock <", value, "stock");
            return (Criteria) this;
        }

        public Criteria andStockLessThanOrEqualTo(Integer value) {
            addCriterion("stock <=", value, "stock");
            return (Criteria) this;
        }

        public Criteria andStockIn(List<Integer> values) {
            addCriterion("stock in", values, "stock");
            return (Criteria) this;
        }

        public Criteria andStockNotIn(List<Integer> values) {
            addCriterion("stock not in", values, "stock");
            return (Criteria) this;
        }

        public Criteria andStockBetween(Integer value1, Integer value2) {
            addCriterion("stock between", value1, value2, "stock");
            return (Criteria) this;
        }

        public Criteria andStockNotBetween(Integer value1, Integer value2) {
            addCriterion("stock not between", value1, value2, "stock");
            return (Criteria) this;
        }

        public Criteria andImagesIsNull() {
            addCriterion("images is null");
            return (Criteria) this;
        }

        public Criteria andImagesIsNotNull() {
            addCriterion("images is not null");
            return (Criteria) this;
        }

        public Criteria andImagesEqualTo(String value) {
            addCriterion("images =", value, "images");
            return (Criteria) this;
        }

        public Criteria andImagesNotEqualTo(String value) {
            addCriterion("images <>", value, "images");
            return (Criteria) this;
        }

        public Criteria andImagesGreaterThan(String value) {
            addCriterion("images >", value, "images");
            return (Criteria) this;
        }

        public Criteria andImagesGreaterThanOrEqualTo(String value) {
            addCriterion("images >=", value, "images");
            return (Criteria) this;
        }

        public Criteria andImagesLessThan(String value) {
            addCriterion("images <", value, "images");
            return (Criteria) this;
        }

        public Criteria andImagesLessThanOrEqualTo(String value) {
            addCriterion("images <=", value, "images");
            return (Criteria) this;
        }

        public Criteria andImagesLike(String value) {
            addCriterion("images like", value, "images");
            return (Criteria) this;
        }

        public Criteria andImagesNotLike(String value) {
            addCriterion("images not like", value, "images");
            return (Criteria) this;
        }

        public Criteria andImagesIn(List<String> values) {
            addCriterion("images in", values, "images");
            return (Criteria) this;
        }

        public Criteria andImagesNotIn(List<String> values) {
            addCriterion("images not in", values, "images");
            return (Criteria) this;
        }

        public Criteria andImagesBetween(String value1, String value2) {
            addCriterion("images between", value1, value2, "images");
            return (Criteria) this;
        }

        public Criteria andImagesNotBetween(String value1, String value2) {
            addCriterion("images not between", value1, value2, "images");
            return (Criteria) this;
        }

        public Criteria andMerchantIdIsNull() {
            addCriterion("merchant_id is null");
            return (Criteria) this;
        }

        public Criteria andMerchantIdIsNotNull() {
            addCriterion("merchant_id is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantIdEqualTo(Integer value) {
            addCriterion("merchant_id =", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdNotEqualTo(Integer value) {
            addCriterion("merchant_id <>", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdGreaterThan(Integer value) {
            addCriterion("merchant_id >", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("merchant_id >=", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdLessThan(Integer value) {
            addCriterion("merchant_id <", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdLessThanOrEqualTo(Integer value) {
            addCriterion("merchant_id <=", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdIn(List<Integer> values) {
            addCriterion("merchant_id in", values, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdNotIn(List<Integer> values) {
            addCriterion("merchant_id not in", values, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdBetween(Integer value1, Integer value2) {
            addCriterion("merchant_id between", value1, value2, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdNotBetween(Integer value1, Integer value2) {
            addCriterion("merchant_id not between", value1, value2, "merchantId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shop_items
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shop_items
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}